#include "colors.h"

const char * colors[] = {
    ANSI_COLOR_RED,
    ANSI_COLOR_GREEN,
    ANSI_COLOR_YELLOW,
    ANSI_COLOR_BLUE,
    ANSI_COLOR_MAGENTA,
    ANSI_COLOR_CYAN,
    ANSI_HIGH_INTENSITY_RED,
    ANSI_HIGH_INTENSITY_GREEN,
    ANSI_HIGH_INTENSITY_BLUE
};